name = "fqs"
uuid = "745789ab-c702-46fa-91c1-49d38df1bd5d"
authors = ["Ioannis Valasakis <code@wizofe.uk> and contributors"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
